on:
  push:
    branches:
      - main
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: purs-eval
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: cachix/install-nix-action@v23
        if: ${{ steps.release.outputs.release_created }}
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v13
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: klarkc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix build
          mkdir -p dist
          cp result/bin/purs-eval dist
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
